### ISSUE TITLE
SCAN command for keyspace with a key parameter?

### ISSUE THREAD

**Issue by Flavio80** [icerlion/FlyRedis#1]
Hello,
I'm trying to use this library in my project and I've found a possible problem. 
The signature of the SCAN function 
`bool CFlyRedisClient::SCAN(const std::string& strKey, int nCursor, const std::string& strMatchPattern, int nCount, int& nResultCursor, std::vector<std::string>& vecResult)
`
is possibly wrong, because the first parameter (strKey) has no meaning if you are trying to scan with a MATCH option in the redis keyspace.

It's instead ok with SSCAN and ZSCAN, where you are looking in the SET or ZSET elements.

Is there a workaround to achieve the same result on Keyspace? Maybe passing an empty key? 

Thanks,
Flavio

**Comment by icerlion** [comment]
Hi:
As the command SCAN was not used Frequently, so maybe there some bugs.
Thanks for your review. I will check the code and fix it ASAP.















--

晓风冰凌




At 2020-05-27 17:13:14, "Flavio80" <notifications@github.com> wrote:

Hello,
I'm trying to use this library in my project and I've found a possible problem.
The signature of the SCAN function
bool CFlyRedisClient::SCAN(const std::string& strKey, int nCursor, const std::string& strMatchPattern, int nCount, int& nResultCursor, std::vector<std::string>& vecResult)
is possibly wrong, because the first parameter (strKey) has no meaning if you are trying to scan with a MATCH option in the redis keyspace.

It's instead ok with SSCAN and ZSCAN, where you are looking in the SET or ZSET elements.

Is there a workaround to achieve the same result on Keyspace? Maybe passing an empty key?

Thanks,
Flavio

**Comment by icerlion** [comment]
After reading the SCAN document, https://redis.io/commands/scan, it reminds me of my initial intention,
in this function, bool CFlyRedisClient::SCAN(const std::string& strKey, int nCursor, const std::string& strMatchPattern, int nCount, int& nResultCursor, std::vector<std::string>& vecResult), the first param strKey, provides a way to resolve the target Redis Server Node.

If you use FlyRedis to connect a standalone redis server, the strKey has no meaning, but if you want to link to Redis Cluster, the strKey will resolve the target redis node in the cluster, which you want to run the SCAN command on.

I will add a override function, to ignore the strKey parameter, which will has the following signature:
bool CFlyRedisClient::SCAN(int nCursor, const std::string& strMatchPattern, int nCount, int& nResultCursor, std::vector<std::string>& vecResult)

Any question, just let me know, thanks for your review again.

**Comment by Flavio80** [comment]
ok then and thanks for the quick check.
Just a question: in the new function you will be able to SCAN only a certain cluster node (and which one, in case)? Or it automatically scan all over the cluster nodes with that pattern?
Regards,
Flavio

**Comment by icerlion** [comment]
It won't automatically scan all over the cluster, which is not a good idea. Well, I make some changes to resolve this problem.

>void CFlyRedisClient::FetchRedisNodeList(std::vector<std::string>& vecRedisNodeList) const
>bool CFlyRedisClient::ChoseCurRedisNode(const std::string& strNodeAddr);

You can call CFlyRedisClient::FetchRedisNodeList to fetach all cluster nodes, then call CFlyRedisClient::ChoseCurRedisNode to chose the target redis session before use SCAN command.

Just like this:
>std::vector<std::string> vecRedisNode;
>hFlyRedisClient.FetchRedisNodeList(vecRedisNode);
>for (auto& strNode : vecRedisNode)
>{
>    hFlyRedisClient.ChoseCurRedisNode(strNode);
>    if (!hFlyRedisClient.SCAN(0, "*", 10, nResult, vecResult))
>    {
>        Logger("SCAN FAILED");
>    }
>}

At the same time, I delete the SCAN function which has the strKey param, as the param strKey may lead to confused.

**Comment by Flavio80** [comment]
> It won't automatically scan all over the cluster, which is not a good idea. Well, I make some changes to resolve this problem.
> 
> > void CFlyRedisClient::FetchRedisNodeList(std::vectorstd::string& vecRedisNodeList) const
> > bool CFlyRedisClient::ChoseCurRedisNode(const std::string& strNodeAddr);
> 
> You can call CFlyRedisClient::FetchRedisNodeList to fetach all cluster nodes, then call CFlyRedisClient::ChoseCurRedisNode to chose the target redis session before use SCAN command.
> 
> Just like this:
> 
> > std::vectorstd::string vecRedisNode;
> > hFlyRedisClient.FetchRedisNodeList(vecRedisNode);
> > for (auto& strNode : vecRedisNode)
> > {
> > hFlyRedisClient.ChoseCurRedisNode(strNode);
> > if (!hFlyRedisClient.SCAN(0, "*", 10, nResult, vecResult))
> > {
> > Logger("SCAN FAILED");
> > }
> > }

That's very good! Eventually we can wrap the ChoseNode/SCAN pattern in a function to achieve the  CLUSTER_SCAN.
Is this feature already available?
Thank you,

**Comment by icerlion** [comment]
Well, it's a good feature. But there is no CLUSTER_SCAN in the offical command list,  [https://redis.io/commands](url)
You can edit the source file and add the CLUSTER_SCAN in your own project, I want to keep consistent with offical command. 
Thank you.

**Comment by Flavio80** [comment]
> Well, it's a good feature. But there is no CLUSTER_SCAN in the offical command list, [https://redis.io/commands](url)
> You can edit the source file and add the CLUSTER_SCAN in your own project, I want to keep consistent with offical command.
> Thank you.

Absolutely.
So the new version is already out?

**Comment by icerlion** [comment]
Yes, you can update it from github.
