### ISSUE TITLE
can't connect to redis node with mnemonic name

### ISSUE THREAD

**Issue by darioluzzi** [icerlion/FlyRedis#2]
this works only using the IP address, not when using a server name

**Comment by icerlion** [comment]
The current version can't not connect to redis with server name, I will fix it ASAP!

**Comment by icerlion** [comment]
I have re-design the connect code, get the lastest code and try the following code:
```
CFlyRedisClient hFlyRedisClient;
hFlyRedisClient.SetRedisConfig("hostname_or_ip", "password");
hFlyRedisClient.Open();
```
Any question, let me know.
