### ISSUE TITLE
TLS support & cluster connectivity 

### ISSUE THREAD

**Issue by dev-konrad** [icerlion/FlyRedis#3]
Hello,

is there any chance this library supports secure communication to Redis Server?
Also, I can see the code related to cluster, so does it mean it was also tested against Redis Enterprise cluster?

Thanks,
Konrad

**Comment by icerlion** [comment]
Well, SSL/TLS is supported by Redis starting with version 6, I could try to implement it in FlyRedis, but it will take a while to finish it.

FlyRedis implement RESP3, it was tested against Redis cluster. 
For more information, it will run as the following step:
1. Create a CFlyRedisSession to connect one redis node.
2. Run redis command "INFO CLUSTER" to resolve the cluster flag
3. If the first CFlyRedisSession saied that the Redis is in cluster mode, it will run "CLUSTER NODES" to get all redis node.
4. Every redis node will describe by one CFlyRedisSession, and every FlyRedisSession will store the slot range.

**Comment by dev-konrad** [comment]
ok, thanks for clarifying @icerlion, having this would be really awesome.

**Comment by icerlion** [comment]
@mruki TLS is done now but not commit to github. I will test the code in the next few days.

**Comment by icerlion** [comment]
@mruki TLS is ready now, define FLY_REDIS_ENABLE_TLS when you compile it. Any question, let me know.
