### ISSUE TITLE
Removed function from previous version

### ISSUE THREAD

**Issue by Flavio80** [icerlion/FlyRedis#4]
Hello,
I've found  that you removed a function in the new version.

void SetRedisReadTimeOutSeconds(int nSeconds);

I included this in my project, so there is a replacement for this? 

Could you please tag your version with date/numbering so we can check when a new version come out? 
Also a release note could be useful.

Thanks,

**Comment by icerlion** [comment]
Well, the function SetRedisReadTimeOutSeconds did not have a good-implement in the previous version. You can comment the function in you project, I will re-implement it in the next version.

Tag is a good idea, I will do it, thanks for your suggestion

**Comment by Flavio80** [comment]
> Well, the function SetRedisReadTimeOutSeconds did not have a good-implement in the previous version. You can comment the function in you project, I will re-implement it in the next version.
> 
> Tag is a good idea, I will do it, thanks for your suggestion

Thanks for the reply. 
So, I have to expect that all the read functions are blocking without a timeout or there is a default timeout (not configurable for now)?

**Comment by icerlion** [comment]
Yes, you are right. Most of the time, the read-time-out is not necessary, actually, the previous SetRedisReadTimeOutSeconds did not work GOOD. but I will fix this issue ASAP.

**Comment by icerlion** [comment]
Hi, @Flavio80 , I have done SetRedisReadTimeOutSeconds, and it's OK on win10. Later I will test it on linux. This weekend, I could release the code.

**Comment by icerlion** [comment]
Hi, @Flavio80 It's done, just check out the latest code.
`CFlyRedisClient hFlyRedisClient;
hFlyRedisClient.SetReadTimeoutSeconds(5);`
