### ISSUE TITLE
pub/sub

### ISSUE THREAD

**Issue by evmins** [icerlion/FlyRedis#5]
Any hope for Subscribe command?

**Comment by icerlion** [comment]
Well, emmmm, actually, pub/sub is not on my list. But if you want it, I will support it ASAP. thank for your suggestion.

**Comment by icerlion** [comment]
> Any hope for Subscribe command?

I want to use async mode when implement subscribe command,  what's your suggestion?

**Comment by icerlion** [comment]
@evmins hi, pub/sub has done, but not committed, I will release the code after deep-test.

**Comment by icerlion** [comment]
Publish/Subscribe has done, you can check out the latest code and try it. Any question, just let me know.
