### ISSUE TITLE
请问 如果主机断开了的话我该怎么重连

### ISSUE THREAD

**Issue by suchmors** [icerlion/FlyRedis#7]
如题所示 如果客户端和主机断开了我该怎么重新连接

**Comment by icerlion** [comment]
已收到反馈，这两天比较忙，晚点整理一份答复给到您。此类短线操作之前测试验证过，内部会自动重连。

**Comment by icerlion** [comment]
@suchmors 经确认，FlyRedis会自动修复断开的网络连接，即如果网络发生闪断的情况，在网络恢复后，FlyRedis会自动重新连接到Redis服务器。
具体执行逻辑为：当投递一条Redis指令的时候，会执行VerifyRedisSessionList这个函数，VerifyRedisSessionList会检测出所有坏掉的指令，并将其自动重新修复。作为调用者，不需要关心此类问题。如果调用者需要知道此事件发生了，在间的到BadSession的时候，你可以添加一条回调函数来获得这件事情的通知。
以上，Thanks for your feedback.
